---
title: "Debate Night Regression"
output: html_notebook
---


### Preprocess data with PCA and scaling

Apply PCA
```{r}
# separate features and target
target <- dataset$botscore
features <- dataset
features$botscore <- NULL

pca <- preProcess(features, method = c("center", "scale", "pca"),
                  thresh = 0.95, pcaComp = NULL)
print(pca)
transformed <- predict(pca, dataset)
summary(transformed)
```

normalize PCA transformed features
```{r}
transformed <- data.frame(transformed)

# separate features and target
target <- transformed$botscore
features <- transformed
features$botscore <- NULL

normalized <- normalize(features, method = "range", range = c(0, 1), 
                             on.constant = "quiet")

# put together processed feature columns and target
preprocessed <- cbind(normalized, target)

# rename target variable
colnames(preprocessed)[8] <- "botscore"

summary(preprocessed)
```


#### Split Train and Test data
```{r}
split_point <- 0.75*nrow(preprocessed)
data_train <- preprocessed[1:split_point,]
data_test <- preprocessed[(split_point+1):nrow(preprocessed),]
```


### Construct Regressor

construct trainControl object
```{r}
regtrain_control <- trainControl(
  method = "repeatedcv",
  number = 10,
  repeats = 10,
  returnResamp = "all"
)
```

```{r}
linRegressor <- train(botscore ~ friendsCount + retweetsCount + listedCount, data = data_train, method = "lm", trControl = regtrain_control)
linRegressor
```


### Implement Artificial Neural Network

Load library
```{r}
library(neuralnet)
```

Train Neural net
```{r}
layer_neurons = c(3,2)

n <- names(data_train)

nn = neuralnet(botscore ~ ., data = data_train, hidden = layer_neurons, 
               stepmax = 10000, threshold = 0.00005,act.fct = "logistic", 
               linear.output = T, algorithm = "sag")
```






