---
title: "R Notebook"
output: html_notebook
---

### Implement Artificial Neural Network

Load library
```{r}
library(neuralnet)
```

Preprocess
```{r}
datar <- datareg

# assign low value for "protected" botscore, assign large value for "suspended" botscore

prot <- which(datar$botscore == "protected")
sus <- which(datar$botscore == "suspended")

randscore <- rnorm(n=length(sus), mean=0.75, sd=0.11)
randscore[which(randscore>1)] <- 1
randscore[which(randscore<0.5)] <- 0.5

randscore2 <- rnorm(n=length(prot), mean=0.15, sd=0.07)
randscore2[which(randscore2>0.3)] <- 0.3
randscore2[which(randscore2<0)] <- 0

datar$botscore[which(datar$botscore == "protected")] <- randscore2
datar$botscore[which(datar$botscore == "suspended")] <- randscore

datar$botscore <- as.numeric(as.character(datar$botscore))
str(datar)
```


Train Neural net
```{r}
layer_neurons = c(3,2)

n <- names(data_train)

nn = neuralnet(isbot ~ ., data = data_train, hidden = layer_neurons, 
               threshold = 0.0005,act.fct = "logistic", 
               linear.output = T, algorithm = "rprop+", learningrate = )
```


```{r}


nn_model <- train(isbot ~ .,
                  data = data_train)
```




